redis-ha:
  enabled: true

controller:
  replicas: 1

server:
  replicas: 1

repoServer:
  replicas: 2

applicationset:
  replicas: 1
  
global::
  domain: backstage-argocd.io

certificates:
  enabled: true

server:
  ingress:
    enabled: true
    port: 80
    className: nginx
    annotations: 
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    hosts:
      - host: argocd.example.com
        paths:
          - path: /
            pathType: Prefix
    tls: []
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"